services:
  app:
    build: .
    container_name: jaapi-fastapi
    ports:
      - "9009:9009"
    volumes:
      - ./scraped_data:/app/scraped_data
    env_file:
      - ./.env
    environment:
      - DATABASE_URL:${DATABASE_URL}
      - PYTHONUNBUFFERED=1
    restart: always
